// Curated fallback when the user's Spotify library cannot be read
// (e.g. Spotify rate limit). 100 well-known Spotify tracks (25 per
// valence/arousal quadrant) with real audio features from the dataset,
// so they are classified exactly without any API or feature lookup.
export const DEMO_TRACKS = [
  // happy
  { spotifyId: "2tTmW7RDtMQtBk7m2rYeSw", title: "Quevedo: Bzrp Music Sessions, Vol. 52", artist: "Bizarrap", valence: 0.55, energy: 0.78, instrumentalness: 0.03, popularity: 99 },
  { spotifyId: "5ww2BF9slyYgNOk37BlC4u", title: "La Bachata", artist: "Manuel Turizo", valence: 0.85, energy: 0.68, instrumentalness: 0.0, popularity: 98 },
  { spotifyId: "4h9wh7iOZ0GGn8QVp4RAOB", title: "I Ain't Worried", artist: "OneRepublic", valence: 0.82, energy: 0.8, instrumentalness: 0.0, popularity: 96 },
  { spotifyId: "4LRPiXqCikLlN15c3yImP7", title: "As It Was", artist: "Harry Styles", valence: 0.66, energy: 0.73, instrumentalness: 0.0, popularity: 95 },
  { spotifyId: "1xzi1Jcr7mEi9K2RfzLOqS", title: "CUFF IT", artist: "Beyoncé", valence: 0.64, energy: 0.69, instrumentalness: 0.0, popularity: 93 },
  { spotifyId: "7dSZ6zGTQx66c2GF91xCrb", title: "PROVENZA", artist: "KAROL G", valence: 0.53, energy: 0.52, instrumentalness: 0.01, popularity: 93 },
  { spotifyId: "0mBP9X2gPCuapvpZ7TGDk3", title: "Left and Right (Feat. Jung Kook of BTS)", artist: "Charlie Puth", valence: 0.72, energy: 0.59, instrumentalness: 0.0, popularity: 92 },
  { spotifyId: "4C6Uex2ILwJi9sZXRdmqXp", title: "Super Freaky Girl", artist: "Nicki Minaj", valence: 0.91, energy: 0.89, instrumentalness: 0.0, popularity: 92 },
  { spotifyId: "0WtM2NBVQNNJLh6scP13H8", title: "Calm Down (with Selena Gomez)", artist: "Rema", valence: 0.8, energy: 0.81, instrumentalness: 0.0, popularity: 92 },
  { spotifyId: "79HZAZNnOE97rb2hnI0XQr", title: "LOKERA", artist: "Rauw Alejandro", valence: 0.58, energy: 0.83, instrumentalness: 0.0, popularity: 91 },
  { spotifyId: "0hquQWY3xvYqN4qtiquniF", title: "Vegas (From the Original Motion Picture Soundtrack ELVIS)", artist: "Doja Cat", valence: 0.74, energy: 0.6, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "4zN21mbAuaD0WqtmaTZZeP", title: "Ferrari", artist: "James Hype", valence: 0.69, energy: 0.69, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "2rurDawMfoKP4uHyb2kJBt", title: "Te Felicito", artist: "Shakira", valence: 0.57, energy: 0.64, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "1797zYiX4cKosMH836X9Gt", title: "La Corriente", artist: "Bad Bunny", valence: 0.58, energy: 0.79, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "7ef4DlsgrMEH11cDZd32M6", title: "One Kiss (with Dua Lipa)", artist: "Calvin Harris", valence: 0.59, energy: 0.86, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "27ZZdyTSQWI7Cug2d2PkqV", title: "BILLIE EILISH.", artist: "Armani White", valence: 0.77, energy: 0.51, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "1PckUlxKqWQs3RlWXVBLw3", title: "About Damn Time", artist: "Lizzo", valence: 0.72, energy: 0.74, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "6UelLqGlWMcVH1E5c4H7lY", title: "Watermelon Sugar", artist: "Harry Styles", valence: 0.56, energy: 0.82, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "5QO79kh1waicV47BqGRL3g", title: "Save Your Tears", artist: "The Weeknd", valence: 0.64, energy: 0.83, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "0HqZX76SFLDz2aW8aiqi7G", title: "Bones", artist: "Imagine Dragons", valence: 0.57, energy: 0.74, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "6Uj1ctrBOjOas8xZXGqKk4", title: "Woman", artist: "Doja Cat", valence: 0.88, energy: 0.76, instrumentalness: 0.0, popularity: 88 },
  { spotifyId: "086myS9r57YsLbJpU0TgK9", title: "Why'd You Only Call Me When You're High?", artist: "Arctic Monkeys", valence: 0.8, energy: 0.63, instrumentalness: 0.0, popularity: 88 },
  { spotifyId: "2HZLXBOnaSRhXStMLrq9fD", title: "Mary On A Cross", artist: "Ghost", valence: 0.56, energy: 0.9, instrumentalness: 0.0, popularity: 88 },
  { spotifyId: "7lQ8MOhq6IN2w8EYcFNSUk", title: "Without Me", artist: "Eminem", valence: 0.66, energy: 0.67, instrumentalness: 0.0, popularity: 88 },
  { spotifyId: "02MWAaffLxlfxAUY7c5dvx", title: "Heat Waves", artist: "Glass Animals", valence: 0.53, energy: 0.53, instrumentalness: 0.0, popularity: 88 },
  // relaxed
  { spotifyId: "3fjN3y5x4hN53rykAN2LHQ", title: "cómo dormiste?", artist: "Rels B", valence: 0.56, energy: 0.43, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "1JSTJqkT5qHq8MDJnJbRE1", title: "Every Breath You Take", artist: "The Police", valence: 0.74, energy: 0.45, instrumentalness: 0.0, popularity: 86 },
  { spotifyId: "4cktbXiXOapiLBMprHFErI", title: "Memories", artist: "Maroon 5", valence: 0.59, energy: 0.33, instrumentalness: 0.0, popularity: 85 },
  { spotifyId: "2Fxmhks0bxGSBdJ92vM42m", title: "bad guy", artist: "Billie Eilish", valence: 0.56, energy: 0.42, instrumentalness: 0.13, popularity: 84 },
  { spotifyId: "50kpGaPAhYJ3sGmk6vplg0", title: "Love Yourself", artist: "Justin Bieber", valence: 0.52, energy: 0.38, instrumentalness: 0.0, popularity: 84 },
  { spotifyId: "3FAJ6O0NOHQV8Mc5Ri6ENp", title: "Heartbreak Anniversary", artist: "Giveon", valence: 0.54, energy: 0.47, instrumentalness: 0.0, popularity: 84 },
  { spotifyId: "4HBZA5flZLE435QTztThqH", title: "Stuck with U (with Justin Bieber)", artist: "Ariana Grande", valence: 0.54, energy: 0.45, instrumentalness: 0.0, popularity: 83 },
  { spotifyId: "0HaRLPnr887lcQM2YQzkff", title: "For My Hand (feat. Ed Sheeran)", artist: "Burna Boy", valence: 0.72, energy: 0.48, instrumentalness: 0.0, popularity: 83 },
  { spotifyId: "08Isz2ETWSBhvIl8UpKYsp", title: "No Love", artist: "Shubh", valence: 0.72, energy: 0.49, instrumentalness: 0.0, popularity: 83 },
  { spotifyId: "6jjYDGxVJsWS0a5wlVF5vS", title: "Butter", artist: "BTS", valence: 0.69, energy: 0.46, instrumentalness: 0.0, popularity: 83 },
  { spotifyId: "2374M0fQpWi3dLnB54qaLX", title: "Africa", artist: "TOTO", valence: 0.73, energy: 0.37, instrumentalness: 0.0, popularity: 83 },
  { spotifyId: "3vkQ5DAB1qQMYO4Mr9zJN6", title: "Gimme! Gimme! Gimme! (A Man After Midnight)", artist: "ABBA", valence: 0.54, energy: 0.49, instrumentalness: 0.01, popularity: 82 },
  { spotifyId: "3fqwjXwUGN6vbzIwvyFMhx", title: "Tennessee Whiskey", artist: "Chris Stapleton", valence: 0.51, energy: 0.37, instrumentalness: 0.01, popularity: 81 },
  { spotifyId: "1fewSx2d5KIZ04wsooEBOz", title: "Space Cadet (feat. Gunna)", artist: "Metro Boomin", valence: 0.64, energy: 0.46, instrumentalness: 0.0, popularity: 81 },
  { spotifyId: "0snQrp1VaY5Pj1YIHRJpRJ", title: "Chaand Baaliyan", artist: "Aditya A", valence: 0.89, energy: 0.4, instrumentalness: 0.0, popularity: 81 },
  { spotifyId: "6i0V12jOa3mr6uu4WYhUBr", title: "Heathens", artist: "Twenty One Pilots", valence: 0.55, energy: 0.4, instrumentalness: 0.0, popularity: 81 },
  { spotifyId: "1EzrEOXmMH3G43AXT1y7pA", title: "I'm Yours", artist: "Jason Mraz", valence: 0.71, energy: 0.44, instrumentalness: 0.0, popularity: 80 },
  { spotifyId: "7AFASza1mXqntmGtbxXprO", title: "changes", artist: "XXXTENTACION", valence: 0.52, energy: 0.31, instrumentalness: 0.0, popularity: 80 },
  { spotifyId: "4m1mqQuy34Nzh0480VR364", title: "Incendeia", artist: "MC Kevin o Chris", valence: 0.86, energy: 0.46, instrumentalness: 0.04, popularity: 80 },
  { spotifyId: "3SdTKo2uVsxFblQjpScoHy", title: "Stand by Me", artist: "Ben E. King", valence: 0.6, energy: 0.31, instrumentalness: 0.0, popularity: 80 },
  { spotifyId: "0eu4C55hL6x29mmeAjytzC", title: "Life Goes On", artist: "Oliver Tree", valence: 0.57, energy: 0.49, instrumentalness: 0.0, popularity: 79 },
  { spotifyId: "6FZDfxM3a3UCqtzo5pxSLZ", title: "Without Me", artist: "Halsey", valence: 0.53, energy: 0.49, instrumentalness: 0.0, popularity: 79 },
  { spotifyId: "18uwL0vNUanqZH0ro2QcOP", title: "comethru", artist: "Jeremy Zucker", valence: 0.61, energy: 0.18, instrumentalness: 0.0, popularity: 79 },
  { spotifyId: "1k1Bqnv2R0uJXQN4u6LKYt", title: "Ain't No Sunshine", artist: "Bill Withers", valence: 0.52, energy: 0.41, instrumentalness: 0.0, popularity: 79 },
  { spotifyId: "745H5CctFr12Mo7cqa1BMH", title: "My Girl", artist: "The Temptations", valence: 0.69, energy: 0.42, instrumentalness: 0.0, popularity: 79 },
  // tense
  { spotifyId: "4uUG5RXrOk84mYEfFvj3cK", title: "I'm Good (Blue)", artist: "David Guetta", valence: 0.3, energy: 0.96, instrumentalness: 0.0, popularity: 98 },
  { spotifyId: "6Sq7ltF9Qa7SNFBsV5Cogx", title: "Me Porto Bonito", artist: "Bad Bunny", valence: 0.42, energy: 0.71, instrumentalness: 0.0, popularity: 97 },
  { spotifyId: "1IHWl5LamUGEuP4ozKQSXZ", title: "Tití Me Preguntó", artist: "Bad Bunny", valence: 0.19, energy: 0.71, instrumentalness: 0.0, popularity: 97 },
  { spotifyId: "5IgjP7X4th6nMNDh4akUHb", title: "Under The Influence", artist: "Chris Brown", valence: 0.31, energy: 0.69, instrumentalness: 0.0, popularity: 96 },
  { spotifyId: "3k3NWokhRRkEPhCzPmV8TW", title: "Ojitos Lindos", artist: "Bad Bunny", valence: 0.27, energy: 0.69, instrumentalness: 0.0, popularity: 95 },
  { spotifyId: "6Xom58OOXk2SoU711L2IXO", title: "Moscow Mule", artist: "Bad Bunny", valence: 0.29, energy: 0.67, instrumentalness: 0.0, popularity: 94 },
  { spotifyId: "2QjOHCTQ1Jl3zawyYOpxh6", title: "Sweater Weather", artist: "The Neighbourhood", valence: 0.4, energy: 0.81, instrumentalness: 0.02, popularity: 93 },
  { spotifyId: "3JvKfv6T31zO0ini8iNItO", title: "Another Love", artist: "Tom Odell", valence: 0.13, energy: 0.54, instrumentalness: 0.0, popularity: 93 },
  { spotifyId: "3F5CgOj3wFlRv51JsHbxhe", title: "Jimmy Cooks (feat. 21 Savage)", artist: "Drake", valence: 0.37, energy: 0.67, instrumentalness: 0.0, popularity: 91 },
  { spotifyId: "41oY4WCTj5kccfesTVFnvN", title: "Tarot", artist: "Bad Bunny", valence: 0.42, energy: 0.68, instrumentalness: 0.0, popularity: 91 },
  { spotifyId: "6i1g5ZRmJZAkDwBaUZ3f2i", title: "Caile", artist: "Luar La L", valence: 0.46, energy: 0.76, instrumentalness: 0.0, popularity: 91 },
  { spotifyId: "0VjIjW4GlUZAMYd2vXMi3b", title: "Blinding Lights", artist: "The Weeknd", valence: 0.33, energy: 0.73, instrumentalness: 0.0, popularity: 91 },
  { spotifyId: "38T0tPVZHcPZyhtOcCP7pF", title: "STAR WALKIN' (League of Legends Worlds Anthem)", artist: "Lil Nas X", valence: 0.31, energy: 0.71, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "4tYFy8ALRjIZvnvSLw5lxN", title: "Party", artist: "Bad Bunny", valence: 0.47, energy: 0.8, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "75FEaRjZTKLhTrFGsfMUXR", title: "Running Up That Hill (A Deal With God)", artist: "Kate Bush", valence: 0.2, energy: 0.55, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "7MXVkk9YMctZqd1Srtv4MB", title: "Starboy", artist: "The Weeknd", valence: 0.49, energy: 0.59, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "58HvfVOeJY7lUuCqF0m3ly", title: "MIDDLE OF THE NIGHT", artist: "Elley Duhé", valence: 0.09, energy: 0.61, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "2eAvDnpXP5W0cVtiI0PUxV", title: "Dandelions", artist: "Ruth B.", valence: 0.45, energy: 0.69, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "0T5iIrXA4p5GsubkhuBIKV", title: "Until I Found You", artist: "Stephen Sanchez", valence: 0.23, energy: 0.51, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "1cKHdTo9u0ZymJdPGSh6nq", title: "I Was Never There", artist: "The Weeknd", valence: 0.15, energy: 0.74, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "1ga4PztXOIw1yBbdUt2X8v", title: "GATÚBELA", artist: "KAROL G", valence: 0.34, energy: 0.86, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "7DbdUf8aHSYoliSjO6LZv6", title: "Sex, Drugs, Etc.", artist: "Beach Weather", valence: 0.47, energy: 0.84, instrumentalness: 0.01, popularity: 90 },
  { spotifyId: "1DIXPcTDzTj8ZMHt3PDt8p", title: "Gangsta's Paradise", artist: "Coolio", valence: 0.39, energy: 0.51, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "5HCyWlXZPP0y6Gqq8TgA20", title: "STAY (with Justin Bieber)", artist: "The Kid LAROI", valence: 0.48, energy: 0.76, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "59nOXPmaKlBfGMDeOVGrIK", title: "WAIT FOR U (feat. Drake & Tems)", artist: "Future", valence: 0.34, energy: 0.64, instrumentalness: 0.0, popularity: 89 },
  // sad_low
  { spotifyId: "3nqQXoyQOWXiESFLlDF1hG", title: "Unholy (feat. Kim Petras)", artist: "Sam Smith", valence: 0.24, energy: 0.47, instrumentalness: 0.0, popularity: 100 },
  { spotifyId: "5Eax0qFko2dh7Rl2lYs3bx", title: "Efecto", artist: "Bad Bunny", valence: 0.23, energy: 0.47, instrumentalness: 0.0, popularity: 96 },
  { spotifyId: "6xGruZOHLs39ZbVccQTuPZ", title: "Glimpse of Us", artist: "Joji", valence: 0.27, energy: 0.32, instrumentalness: 0.0, popularity: 94 },
  { spotifyId: "31i56LZnwE6uSu3exoHjtB", title: "Neverita", artist: "Bad Bunny", valence: 0.43, energy: 0.5, instrumentalness: 0.0, popularity: 93 },
  { spotifyId: "5XeFesFbtLpXzIVDNQP22n", title: "I Wanna Be Yours", artist: "Arctic Monkeys", valence: 0.48, energy: 0.42, instrumentalness: 0.02, popularity: 92 },
  { spotifyId: "1Fid2jjqsHViMX6xNH70hE", title: "Atlantis", artist: "Seafret", valence: 0.21, energy: 0.48, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "3WMj8moIAXJhHsyLaqIIHI", title: "Something in the Orange", artist: "Zach Bryan", valence: 0.15, energy: 0.19, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "0u2P5u6lvoDfwTYjAADbn4", title: "lovely (with Khalid)", artist: "Billie Eilish", valence: 0.12, energy: 0.3, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "7795WJLVKJoAyVoOtCWqXN", title: "I'm Not The Only One", artist: "Sam Smith", valence: 0.49, energy: 0.48, instrumentalness: 0.0, popularity: 88 },
  { spotifyId: "5wANPM4fQCJwkGd4rN57mH", title: "drivers license", artist: "Olivia Rodrigo", valence: 0.14, energy: 0.43, instrumentalness: 0.0, popularity: 88 },
  { spotifyId: "5CZ40GBx1sQ9agT82CLQCT", title: "traitor", artist: "Olivia Rodrigo", valence: 0.08, energy: 0.34, instrumentalness: 0.0, popularity: 88 },
  { spotifyId: "4RVwu0g32PAqgUiJoXsdF8", title: "Happier Than Ever", artist: "Billie Eilish", valence: 0.3, energy: 0.23, instrumentalness: 0.0, popularity: 88 },
  { spotifyId: "2TktkzfozZifbQhXjT6I33", title: "Evergreen (You Didn’t Deserve Me At All)", artist: "Omar Apollo", valence: 0.31, energy: 0.34, instrumentalness: 0.01, popularity: 88 },
  { spotifyId: "5TXDeTFVRVY7Cvt0Dw4vWW", title: "Revenge", artist: "XXXTENTACION", valence: 0.18, energy: 0.25, instrumentalness: 0.0, popularity: 87 },
  { spotifyId: "0tgVpDi06FyKpA1z0VMD4v", title: "Perfect", artist: "Ed Sheeran", valence: 0.17, energy: 0.45, instrumentalness: 0.0, popularity: 87 },
  { spotifyId: "7qEHsqek33rTcFNT9PFqLf", title: "Someone You Loved", artist: "Lewis Capaldi", valence: 0.45, energy: 0.41, instrumentalness: 0.0, popularity: 87 },
  { spotifyId: "4xqrdfXkTW4T0RauPLv3WA", title: "Heather", artist: "Conan Gray", valence: 0.27, energy: 0.42, instrumentalness: 0.0, popularity: 87 },
  { spotifyId: "3ZCTVFBt2Brf31RLEnCkWJ", title: "everything i wanted", artist: "Billie Eilish", valence: 0.24, energy: 0.23, instrumentalness: 0.66, popularity: 86 },
  { spotifyId: "2ZRo7axmMPeSVUvDbGkJah", title: "Hope", artist: "XXXTENTACION", valence: 0.23, energy: 0.46, instrumentalness: 0.0, popularity: 86 },
  { spotifyId: "2tGvwE8GcFKwNdAXMnlbfl", title: "happier", artist: "Olivia Rodrigo", valence: 0.34, energy: 0.44, instrumentalness: 0.0, popularity: 86 },
  { spotifyId: "70LcF31zb1H0PyJoS1Sx1r", title: "Creep", artist: "Radiohead", valence: 0.1, energy: 0.43, instrumentalness: 0.0, popularity: 85 },
  { spotifyId: "0gplL1WMoJ6iYaPgMCL0gX", title: "Easy On Me", artist: "Adele", valence: 0.13, energy: 0.37, instrumentalness: 0.0, popularity: 85 },
  { spotifyId: "04sN26COy28wTXYj3dMoiZ", title: "Bored", artist: "Billie Eilish", valence: 0.11, energy: 0.32, instrumentalness: 0.0, popularity: 85 },
  { spotifyId: "1HNkqx9Ahdgi1Ixy2xkKkL", title: "Photograph", artist: "Ed Sheeran", valence: 0.2, energy: 0.38, instrumentalness: 0.0, popularity: 85 },
  { spotifyId: "2bRKxuH1o7pTmb1y4GfdEc", title: "Clean White Noise - Loopable with no fade", artist: "White Noise Baby Sleep", valence: 0.0, energy: 0.0, instrumentalness: 1.0, popularity: 85 },
];
